// Code generated by "stringer -type=T"; DO NOT EDIT.

package enum_test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-0]
	_ = x[B-1]
	_ = x[C-2]
}

const _T_name = "ABC"

var _T_index = [...]uint8{0, 1, 2, 3}

func (i T) String() string {
	if i < 0 || i >= T(len(_T_index)-1) {
		return "T(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _T_name[_T_index[i]:_T_index[i+1]]
}
